// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYCqbsOLjODZp9fBC3OXqFzY1PIxwtCew',
    appId: '1:787483996423:web:6ed69a11e121c2cba415a2',
    messagingSenderId: '787483996423',
    projectId: 'chatapp-406bf',
    authDomain: 'chatapp-406bf.firebaseapp.com',
    storageBucket: 'chatapp-406bf.appspot.com',
    measurementId: 'G-8BHT30JJ41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOrFyCAbf90qV9tqrMiyqJ7EWxNnwiUpg',
    appId: '1:787483996423:android:7e9f4edd6d8d8735a415a2',
    messagingSenderId: '787483996423',
    projectId: 'chatapp-406bf',
    storageBucket: 'chatapp-406bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDftdNFsUlW6bprS7CVBAN9BgY8TyQ_ta4',
    appId: '1:787483996423:ios:f7fb14a0d790d842a415a2',
    messagingSenderId: '787483996423',
    projectId: 'chatapp-406bf',
    storageBucket: 'chatapp-406bf.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDftdNFsUlW6bprS7CVBAN9BgY8TyQ_ta4',
    appId: '1:787483996423:ios:f7fb14a0d790d842a415a2',
    messagingSenderId: '787483996423',
    projectId: 'chatapp-406bf',
    storageBucket: 'chatapp-406bf.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYCqbsOLjODZp9fBC3OXqFzY1PIxwtCew',
    appId: '1:787483996423:web:30f8452be584fe23a415a2',
    messagingSenderId: '787483996423',
    projectId: 'chatapp-406bf',
    authDomain: 'chatapp-406bf.firebaseapp.com',
    storageBucket: 'chatapp-406bf.appspot.com',
    measurementId: 'G-39RE20NYPT',
  );
}
